spring:
  datasource:
    url: jdbc:postgresql://77.222.46.203:5432/Clop
    username: postgres
    password: 12Hiro0016
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        spatial:
          dialect: org.hibernate.spatial.dialect.postgis.PostgisPG95Dialect
  web:
    cors:
      allowed-origins: "*"
      allowed-methods: GET,POST,PUT,DELETE,PATCH,OPTIONS
      allowed-headers: "*"
      allow-credentials: false

jwt:
  secret: your-super-secret-key-that-is-at-least-256-bits-long
  expiration: 86400000 # 24
  issuer: user-service

server:
  port: 3001

springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
    try-it-out-enabled: true
    filter: true
    persist-authorization: true
    display-request-duration: true
    groups-order: asc
    enabled: true
  show-actuator: false

logging:
  level:
    com.example.userservice: DEBUG
